---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    container:
      image: erlang:${{matrix.otp_vsn}}
    strategy:
      matrix:
        otp_vsn: [18.0, 18.1, 18.2, 19.3]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: rebar3 compile
